language: python
python: 2.7

sudo: required
dist: trusty

env:
  global:
    - >
      STATUS=$'curl -so/dev/null --user "$EMBARC_BOT" --request POST
      https://api.github.com/repos/$TRAVIS_REPO_SLUG/statuses/${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
      --data @- << DATA\n{
      "state": "$0",
      "description": "$1",
      "context": "travis-ci/$NAME",
      "target_url": "https://travis-ci.org/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
      }\nDATA'
    - EXPECTED=".travis/expected.ini"

cache:
  pip: true
  directories:
    - $HOME/.cache/result
    - $HOME/.cache/toolchain 

before_install:
  - bash .travis/before_install.sh

after_success:
  - bash -c "$STATUS" success "Local $NAME testing has passed"

after_failure:
  - bash -c "$STATUS" failure "Local $NAME testing has failed"

script:
  - bash .travis/script.sh

matrix:
  include:
    - env: NAME="gnu-201709" BSP_ROOT="." TOOLCHAIN="gnu" GNU_VER="2017.09" EXAMPLES="example/hello/arcgnu"
      os: linux
      compiler: gcc
    - env: NAME="gnu-201803" BSP_ROOT="." TOOLCHAIN="gnu" GNU_VER="2018.03" EXAMPLES="example/hello/arcgnu"
      os: linux
      compiler: gcc   
